//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenWeatherMap.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WeatherConditionCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeatherConditionCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenWeatherMap.Resources.Strings.WeatherConditionCodes", typeof(WeatherConditionCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with light rain.
        /// </summary>
        internal static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with rain.
        /// </summary>
        internal static string _201 {
            get {
                return ResourceManager.GetString("201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with heavy rain.
        /// </summary>
        internal static string _202 {
            get {
                return ResourceManager.GetString("202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light thunderstorm.
        /// </summary>
        internal static string _210 {
            get {
                return ResourceManager.GetString("210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm.
        /// </summary>
        internal static string _211 {
            get {
                return ResourceManager.GetString("211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy thunderstorm.
        /// </summary>
        internal static string _212 {
            get {
                return ResourceManager.GetString("212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremely heavy thunderstorm.
        /// </summary>
        internal static string _221 {
            get {
                return ResourceManager.GetString("221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with light drizzle.
        /// </summary>
        internal static string _230 {
            get {
                return ResourceManager.GetString("230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with drizzle.
        /// </summary>
        internal static string _231 {
            get {
                return ResourceManager.GetString("231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with heavy drizzle.
        /// </summary>
        internal static string _232 {
            get {
                return ResourceManager.GetString("232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light intensity drizzle.
        /// </summary>
        internal static string _300 {
            get {
                return ResourceManager.GetString("300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle.
        /// </summary>
        internal static string _301 {
            get {
                return ResourceManager.GetString("301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy intensity drizzle.
        /// </summary>
        internal static string _302 {
            get {
                return ResourceManager.GetString("302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light intensity drizzle rain.
        /// </summary>
        internal static string _310 {
            get {
                return ResourceManager.GetString("310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle rain.
        /// </summary>
        internal static string _311 {
            get {
                return ResourceManager.GetString("311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy intensity drizzle rain.
        /// </summary>
        internal static string _312 {
            get {
                return ResourceManager.GetString("312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower rain and drizzle.
        /// </summary>
        internal static string _313 {
            get {
                return ResourceManager.GetString("313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy shower rain and drizzle.
        /// </summary>
        internal static string _314 {
            get {
                return ResourceManager.GetString("314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower drizzle.
        /// </summary>
        internal static string _321 {
            get {
                return ResourceManager.GetString("321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light rain.
        /// </summary>
        internal static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate rain.
        /// </summary>
        internal static string _501 {
            get {
                return ResourceManager.GetString("501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy intensity rain.
        /// </summary>
        internal static string _502 {
            get {
                return ResourceManager.GetString("502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very heavy rain.
        /// </summary>
        internal static string _503 {
            get {
                return ResourceManager.GetString("503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme rain.
        /// </summary>
        internal static string _504 {
            get {
                return ResourceManager.GetString("504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing rain.
        /// </summary>
        internal static string _511 {
            get {
                return ResourceManager.GetString("511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light intensity shower rain.
        /// </summary>
        internal static string _520 {
            get {
                return ResourceManager.GetString("520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower rain.
        /// </summary>
        internal static string _521 {
            get {
                return ResourceManager.GetString("521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy intensity shower rain.
        /// </summary>
        internal static string _522 {
            get {
                return ResourceManager.GetString("522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme shower rain.
        /// </summary>
        internal static string _531 {
            get {
                return ResourceManager.GetString("531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light snow.
        /// </summary>
        internal static string _600 {
            get {
                return ResourceManager.GetString("600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string _601 {
            get {
                return ResourceManager.GetString("601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy snow.
        /// </summary>
        internal static string _602 {
            get {
                return ResourceManager.GetString("602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleet.
        /// </summary>
        internal static string _611 {
            get {
                return ResourceManager.GetString("611", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light shower sleet.
        /// </summary>
        internal static string _612 {
            get {
                return ResourceManager.GetString("612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower sleet.
        /// </summary>
        internal static string _613 {
            get {
                return ResourceManager.GetString("613", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light rain and snow.
        /// </summary>
        internal static string _615 {
            get {
                return ResourceManager.GetString("615", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain and snow.
        /// </summary>
        internal static string _616 {
            get {
                return ResourceManager.GetString("616", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light shower snow.
        /// </summary>
        internal static string _620 {
            get {
                return ResourceManager.GetString("620", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower snow.
        /// </summary>
        internal static string _621 {
            get {
                return ResourceManager.GetString("621", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy shower snow.
        /// </summary>
        internal static string _622 {
            get {
                return ResourceManager.GetString("622", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mist.
        /// </summary>
        internal static string _701 {
            get {
                return ResourceManager.GetString("701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke.
        /// </summary>
        internal static string _711 {
            get {
                return ResourceManager.GetString("711", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haze.
        /// </summary>
        internal static string _721 {
            get {
                return ResourceManager.GetString("721", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand/dust whirls.
        /// </summary>
        internal static string _731 {
            get {
                return ResourceManager.GetString("731", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        internal static string _741 {
            get {
                return ResourceManager.GetString("741", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand.
        /// </summary>
        internal static string _751 {
            get {
                return ResourceManager.GetString("751", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dust.
        /// </summary>
        internal static string _761 {
            get {
                return ResourceManager.GetString("761", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcanic ash.
        /// </summary>
        internal static string _762 {
            get {
                return ResourceManager.GetString("762", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squalls.
        /// </summary>
        internal static string _771 {
            get {
                return ResourceManager.GetString("771", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tornado.
        /// </summary>
        internal static string _781 {
            get {
                return ResourceManager.GetString("781", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sky.
        /// </summary>
        internal static string _800 {
            get {
                return ResourceManager.GetString("800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Few clouds: 11-25%.
        /// </summary>
        internal static string _801 {
            get {
                return ResourceManager.GetString("801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scattered clouds: 25-50%.
        /// </summary>
        internal static string _802 {
            get {
                return ResourceManager.GetString("802", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken clouds: 51-84%.
        /// </summary>
        internal static string _803 {
            get {
                return ResourceManager.GetString("803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast clouds: 85-100%.
        /// </summary>
        internal static string _804 {
            get {
                return ResourceManager.GetString("804", resourceCulture);
            }
        }
    }
}
