<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <!--NuGet package-->
  <PropertyGroup>
    <Product>OpenWeatherMap.API</Product>
    <Description>OpenWeatherMap API client for .NET</Description>
    <Version>1.0.0</Version>
    <Authors>Thomas Galliker</Authors>
    <PackageId>OpenWeatherMap.API</PackageId>
    <PackageTags>OpenWeatherMap;Weather;API;Forecast;Temperature;Precipitation</PackageTags>
    <PackageIcon>logo.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/thomasgalliker/OpenWeatherMap.API</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/thomasgalliker/OpenWeatherMap.API</RepositoryUrl>
    <Company>superdev GmbH</Company>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Copyright>Copyright $([System.DateTime]::Now.ToString(`yyyy`)) © Thomas Galliker</Copyright>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../ReleaseNotes.txt"))</PackageReleaseNotes>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedAllSources>true</EmbedAllSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\LICENSE" Pack="True" PackagePath="\" />
    <None Include="..\logo.png" Pack="True" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
    <PackageReference Include="UnitsNet" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\*.png" />
    <EmbeddedResource Include="Resources\Icons\*.png" />
  </ItemGroup>

  <PropertyGroup Label="MultilingualAppToolkit">
    <MultilingualAppToolkitVersion>4.0</MultilingualAppToolkitVersion>
    <MultilingualFallbackLanguage>sv</MultilingualFallbackLanguage>
    <TranslationReport Condition="'$(Configuration)' == 'Release'">true</TranslationReport>
    <SuppressPseudoWarning Condition="'$(Configuration)' == 'Debug'">true</SuppressPseudoWarning>
  </PropertyGroup>
  <ItemGroup>
    <XliffResource Include="MultilingualResources\OpenWeatherMap.de.xlf" />
    <XliffResource Include="MultilingualResources\OpenWeatherMap.en.xlf" />
    <XliffResource Include="MultilingualResources\OpenWeatherMap.fr.xlf" />
    <XliffResource Include="MultilingualResources\OpenWeatherMap.it.xlf" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\Strings\AirQualityTranslations.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AirQualityTranslations.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Strings\CardinalWindDirectionsAcronyms.Designer.cs">
      <DependentUpon>CardinalWindDirectionsAcronyms.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Strings\HumidityRanges.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HumidityRanges.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Strings\PressureRanges.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PressureRanges.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Strings\UVIndexRanges.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UVIndexRanges.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Strings\CardinalWindDirections.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CardinalWindDirections.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Strings\WeatherConditionCodes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WeatherConditionCodes.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings\AirQualityTranslations.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AirQualityTranslations.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings\CardinalWindDirectionsAcronyms.resx">
      <LastGenOutput>CardinalWindDirectionsAcronyms.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings\HumidityRanges.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>HumidityRanges.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings\PressureRanges.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>PressureRanges.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings\UVIndexRanges.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>UVIndexRanges.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings\CardinalWindDirections.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>CardinalWindDirections.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings\WeatherConditionCodes.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>WeatherConditionCodes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
